---
build_from:
  aarch64: arm64v8/alpine:3.24
  amd64: amd64/alpine:3.24
  armhf: arm32v6/alpine:3.24
  armv7: arm32v7/alpine:3.24
  i386: i386/alpine:3.24
codenotary:
  signer: codenotary@frenck.dev
